/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bpzilxqg2bfrvczjbf2aomayb4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v2ov3klef5dxrlq3oh35oosxli",
    "aws_cognito_identity_pool_id": "us-east-1:f676f7b5-5a49-430f-9503-3f5202365444",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u59QVOtnS",
    "aws_user_pools_web_client_id": "18o14408s2ql3u37k73d9882b3",
    "oauth": {}
};


export default awsmobile;
